export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const CREATE_NEW_STUDENT_RECORD = 'CREATE_NEW_STUDENT_RECORD';
export const EDIT_STUDENT_RECORD = 'EDIT_STUDENT_RECORD';
export const DELETE_STUDENT_RECORD = 'DELETE_STUDENT_RECORD';
export const FETCH_STUDENTS_RECORDS_REQUEST = 'FETCH_STUDENTS_RECORDS_REQUEST';
export const FETCH_STUDENTS_RECORDS_SUCCESS = 'FETCH_STUDENTS_RECORDS_SUCCESS';
export const FETCH_STUDENTS_RECORDS_FAIL = 'FETCH_STUDENTS_RECORDS_FAIL';

export const CREATE_NEW_GRADE_RECORD = 'CREATE_NEW_GRADE_RECORD';
export const EDIT_GRADE_RECORD = 'EDIT_GRADE_RECORD';
export const DELETE_GRADE_RECORDS = 'DELETE_GRADE_RECORDS';
export const FETCH_GRADES_RECORDS_REQUEST = 'FETCH_GRADES_RECORDS_REQUEST';
export const FETCH_GRADES_RECORDS_SUCCESS = 'FETCH_GRADES_RECORDS_SUCCESS';
export const FETCH_GRADES_RECORDS_FAIL = 'FETCH_GRADES_RECORDS_FAIL';
